"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ReportItem } from "@/types/report";
import { FileText, Download, Eye, Bot, Sparkles, Filter, CheckCircle2 } from "lucide-react";

interface ReportTableProps {
  reports: ReportItem[];
  onViewReport?: (report: ReportItem) => void;
}

export function ReportTable({ reports, onViewReport }: ReportTableProps) {
  const [selectedType, setSelectedType] = useState<string>("All");
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  const reportTypes = ["All", "Portfolio", "Multi-Agent", "Tax", "Risk", "Market", "Credit"];

  const filteredReports = reports.filter((r) => {
    if (selectedType === "All") return true;
    return r.type === selectedType;
  });

  const handleDownload = (r: ReportItem) => {
    setDownloadingId(r.id);
    setTimeout(() => {
      setDownloadingId(null);
      const element = document.createElement("a");
      const file = new Blob([
        `FINOS INSTITUTIONAL INTELLIGENCE DOSSIER\n\nTitle: ${r.title}\nType: ${r.type}\nGenerated: ${r.generatedDate}\nStatus: ${r.status}\n\nContributing Agents: ${r.contributingAgents.join(", ")}\n\nEXECUTIVE HIGHLIGHTS:\n${r.highlights.map(h => "- " + h).join("\n")}\n\n[FinOS Cryptographic Proof: SHA-256-verified institutional ledger]`
      ], { type: "text/plain" });
      element.href = URL.createObjectURL(file);
      element.download = `${r.title.toLowerCase().replace(/[^a-z0-9]/g, "_")}.txt`;
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    }, 800);
  };

  return (
    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden shadow-xs">
      {/* Filter Tabs */}
      <div className="p-4 sm:p-5 border-b border-slate-100 dark:border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h3 className="text-base font-bold text-slate-900 dark:text-white">Institutional Dossier Archive</h3>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            Audit-ready synthesized intelligence reports generated by FinOS multi-agent pipelines
          </p>
        </div>

        <div className="flex items-center gap-1.5 overflow-x-auto py-1">
          {reportTypes.map((type) => (
            <button
              key={type}
              onClick={() => setSelectedType(type)}
              className={`relative px-3 py-1 text-xs font-semibold rounded-lg whitespace-nowrap transition-colors ${
                selectedType === type
                  ? "text-slate-900 dark:text-white"
                  : "text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white"
              }`}
            >
              {selectedType === type && (
                <motion.div
                  layoutId="activeReportType"
                  transition={{ type: "spring", stiffness: 500, damping: 35 }}
                  className="absolute inset-0 bg-slate-100 dark:bg-slate-800 rounded-lg -z-0"
                />
              )}
              <span className="relative z-10">{type}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Reports List */}
      <div className="divide-y divide-slate-100 dark:divide-slate-800">
        {filteredReports.length === 0 ? (
          <div className="py-12 p-6 text-center space-y-2">
            <h3 className="text-sm font-bold text-slate-900 dark:text-white">
              No financial dossiers archived
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 max-w-sm mx-auto">
              Click &quot;Generate New Dossier&quot; or execute an analysis on the Ask FinOS page to generate an audit report.
            </p>
          </div>
        ) : (
          <AnimatePresence mode="popLayout">
            {filteredReports.map((report) => (

            <motion.div
              key={report.id}
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -4 }}
              transition={{ duration: 0.2 }}
              className="p-4 sm:p-5 hover:bg-slate-50/70 dark:hover:bg-slate-800/40 transition-colors flex flex-col lg:flex-row lg:items-center justify-between gap-4"
            >
              <div className="space-y-1.5 flex-1">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 border border-emerald-200/80 dark:border-emerald-800/50">
                    {report.type}
                  </span>
                  <span className="text-xs text-slate-400">
                    Published {report.generatedDate}
                  </span>
                  <span className="text-[10px] font-mono font-medium px-1.5 py-0.5 rounded bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400">
                    {report.format} • {report.fileSize}
                  </span>
                </div>

                <h4 className="text-sm sm:text-base font-bold text-slate-900 dark:text-white leading-snug">
                  {report.title}
                </h4>
                <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed max-w-3xl">
                  {report.subtitle}
                </p>

                {/* Highlights Preview */}
                <div className="pt-1.5 space-y-1">
                  {report.highlights.slice(0, 2).map((h, i) => (
                    <div key={i} className="flex items-center gap-2 text-xs text-slate-600 dark:text-slate-300">
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
                      <span className="truncate">{h}</span>
                    </div>
                  ))}
                </div>

                {/* Contributing Agents */}
                <div className="flex items-center gap-2 pt-2 text-[11px] text-slate-400">
                  <Bot className="w-3.5 h-3.5 text-slate-400" />
                  <span>Collaborating Agents:</span>
                  <div className="flex items-center gap-1.5">
                    {report.contributingAgents.map((ag) => (
                      <span
                        key={ag}
                        className="px-1.5 py-0.2 rounded text-[10px] uppercase font-mono font-semibold bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300"
                      >
                        {ag}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              {/* Actions */}
              <div className="flex items-center gap-2 self-start lg:self-center shrink-0">
                <button
                  onClick={() => onViewReport && onViewReport(report)}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-xs font-semibold text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors"
                >
                  <Eye className="w-3.5 h-3.5" />
                  <span>View Summary</span>
                </button>

                <motion.button
                  whileTap={{ scale: 0.95 }}
                  onClick={() => handleDownload(report)}
                  disabled={downloadingId === report.id}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold shadow-xs transition-colors disabled:opacity-50"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>{downloadingId === report.id ? "Preparing..." : "Export"}</span>
                </motion.button>
              </div>
            </motion.div>
          ))}
        </AnimatePresence>
        )}
      </div>
    </div>
  );
}

