"use client";

import React, { useState } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { ReportTable } from "@/components/reports/ReportTable";
import { GenerateReportModal } from "@/components/reports/GenerateReportModal";
import { MOCK_REPORTS } from "@/lib/mock/reports";
import { ReportItem } from "@/types/report";
import {
  FileText,
  Plus,
  Sparkles,
  Bot,
  ShieldCheck,
  CheckCircle2,
  X,
  Download,
} from "lucide-react";

export default function ReportsPage() {
  const [reports, setReports] = useState<ReportItem[]>(MOCK_REPORTS);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedReport, setSelectedReport] = useState<ReportItem | null>(null);

  const handleGenerated = (newTitle: string) => {
    const newDoc: ReportItem = {
      id: `rep-${Date.now()}`,
      title: newTitle,
      subtitle: "Custom institutional synthesis generated by FinOS collaborative multi-agent pipeline.",
      type: "Multi-Agent",
      generatedDate: "Just now",
      contributingAgents: ["portfolio", "macro", "risk"],
      status: "Ready",
      format: "PDF",
      fileSize: "2.4 MB",
      highlights: [
        "Multi-agent consensus resolved with 89% weighted agreement",
        "Deterministic risk guardrails verified with zero threshold violations",
        "Full citation trace indexed in FinOS GraphRAG memory",
      ],
    };
    setReports([newDoc, ...reports]);
  };

  return (
    <AppShell
      headerTitle="Financial Reports"
      headerSubtitle="Synthesized institutional dossiers generated by collaborative multi-agent pipelines"
    >
      <div className="space-y-6">
        {/* Banner */}
        <section className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 sm:p-6 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold uppercase tracking-wider text-violet-600 dark:text-violet-400">
                Institutional Documentation
              </span>
              <span className="text-slate-300 dark:text-slate-700">•</span>
              <span className="text-xs text-slate-500 font-mono">Audit Ready</span>
            </div>
            <h1 className="text-xl sm:text-2xl font-black text-slate-950 dark:text-white tracking-tight">
              Synthesized Financial Dossiers
            </h1>
            <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 max-w-2xl">
              Comprehensive memos generated by collaborative agent workflows. Each dossier includes mathematical factor breakdowns, sovereign regulatory compliance notes, and tamper-proof audit trails.
            </p>
          </div>

          <button
            onClick={() => setIsModalOpen(true)}
            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-violet-600 hover:bg-violet-700 text-white text-xs font-bold shadow-md shadow-violet-600/20 transition-all self-start md:self-center"
          >
            <Plus className="w-4 h-4" />
            <span>Generate New Dossier</span>
          </button>
        </section>

        {/* Report Archive Table */}
        <ReportTable reports={reports} onViewReport={(r) => setSelectedReport(r)} />

        {/* Selected Report Inspection Modal / Drawer */}
        {selectedReport && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/60 backdrop-blur-xs animate-in fade-in">
            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl max-w-2xl w-full p-6 shadow-2xl relative">
              <button
                onClick={() => setSelectedReport(null)}
                className="absolute top-4 right-4 p-1.5 rounded-lg text-slate-400 hover:text-slate-700 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
              >
                <X className="w-5 h-5" />
              </button>

              <div className="flex items-center gap-2 mb-2">
                <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-violet-100 dark:bg-violet-950/60 text-violet-700 dark:text-violet-300">
                  {selectedReport.type} Dossier
                </span>
                <span className="text-xs text-slate-400">{selectedReport.generatedDate}</span>
              </div>

              <h3 className="text-lg font-bold text-slate-950 dark:text-white mb-1.5">
                {selectedReport.title}
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed mb-4">
                {selectedReport.subtitle}
              </p>

              <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/80 space-y-3 mb-5">
                <div className="text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300">
                  Executive Highlights &amp; Findings
                </div>
                <div className="space-y-2">
                  {selectedReport.highlights.map((h, i) => (
                    <div key={i} className="flex items-start gap-2.5 text-xs text-slate-700 dark:text-slate-300">
                      <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                      <span>{h}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="flex items-center justify-between text-xs text-slate-400 border-t border-slate-100 dark:border-slate-800 pt-4">
                <div className="flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-emerald-500" />
                  <span>SHA-256 Ledger Verified</span>
                </div>
                <button
                  onClick={() => setSelectedReport(null)}
                  className="px-4 py-2 rounded-lg bg-slate-900 dark:bg-white text-white dark:text-slate-900 text-xs font-bold"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Generate Report Dialog */}
        <GenerateReportModal
          isOpen={isModalOpen}
          onClose={() => setIsModalOpen(false)}
          onGenerated={handleGenerated}
        />
      </div>
    </AppShell>
  );
}
