"use client";

import React, { useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { AppShell } from "@/components/layout/AppShell";
import { getAnalysisRecordById, MOCK_ANALYSIS_RECORDS } from "@/lib/mock/analysis";
import { ALL_AGENTS } from "@/lib/mock/agents";
import {
  ArrowLeft,
  Sparkles,
  Bot,
  CheckCircle2,
  AlertTriangle,
  FileText,
  RotateCcw,
  Download,
  Share2,
  TrendingUp,
  Cpu,
  Layers,
  ArrowRight,
  ShieldAlert,
  Loader2,
  Check,
  Eye,
  Calendar,
  ExternalLink,
} from "lucide-react";

export default function AnalysisDetailPage() {
  const params = useParams();
  const router = useRouter();
  const id = typeof params.id === "string" ? params.id : Array.isArray(params.id) ? params.id[0] : "";

  // Retrieve matching record
  const record = getAnalysisRecordById(id);

  if (!record) {
    return (
      <AppShell headerTitle="Analysis Dossier" headerSubtitle="Historical analysis query">
        <div className="max-w-xl mx-auto py-16 text-center space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-slate-100 dark:bg-slate-800 text-slate-400 flex items-center justify-center mx-auto">
            <AlertTriangle className="w-6 h-6 text-amber-500" />
          </div>
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">
            Analysis Dossier Unavailable
          </h2>
          <p className="text-xs text-slate-500">
            The requested analysis record was not found or has expired. Please execute a new inquiry in the Ask FinOS workspace.
          </p>
          <Link
            href="/ask"
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-emerald-600 text-white text-xs font-bold shadow-xs hover:bg-emerald-700 transition"
          >
            <span>Go to Ask FinOS</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>
      </AppShell>
    );
  }

  const [isRerunning, setIsRerunning] = useState(false);

  const [rerunStage, setRerunStage] = useState<string>("");
  const [reportState, setReportState] = useState<"idle" | "generating" | "ready">("idle");
  const [generatedReportText, setGeneratedReportText] = useState("");

  const handleRerun = () => {
    setIsRerunning(true);
    setRerunStage("1. Identifying relevant AI agents...");

    setTimeout(() => {
      setRerunStage("2. Agent cross-collaboration & real-time telemetry ingest...");
    }, 900);

    setTimeout(() => {
      setRerunStage("3. Running Decision Engine & conflict resolution...");
    }, 1800);

    setTimeout(() => {
      setRerunStage("4. Synthesizing unified institutional insight...");
    }, 2600);

    setTimeout(() => {
      setIsRerunning(false);
      setRerunStage("");
    }, 3400);
  };

  const handleGenerateReport = () => {
    setReportState("generating");
    setTimeout(() => {
      const reportContent = `FINOS INSTITUTIONAL INTELLIGENCE DOSSIER
=====================================================
Title: ${record.title}
Query: "${record.query}"
Category: ${record.type}
Date: ${record.date} (${record.timestamp})
Status: ${record.status}
Agents Consulted: ${record.agentsUsed.join(", ")}

EXECUTIVE SUMMARY:
-----------------------------------------------------
${record.summary}

KEY FINDINGS & TELEMETRY:
-----------------------------------------------------
${record.keyFindings.map((f, i) => `${i + 1}. ${f}`).join("\n")}

${record.marketInfo ? `MARKET INFORMATION:
-----------------------------------------------------
Symbol: ${record.marketInfo.symbol || "N/A"}
Price: ${record.marketInfo.price || "N/A"} (${record.marketInfo.change || "N/A"})
P/E Ratio: ${record.marketInfo.peRatio || "N/A"}
Market Cap: ${record.marketInfo.marketCap || "N/A"}
Volume: ${record.marketInfo.volume || "N/A"}
` : ""}
RISK FACTORS:
-----------------------------------------------------
${record.riskFactors.map((r, i) => `[${r.impact} IMPACT] ${r.factor}: ${r.description}`).join("\n")}

INVESTMENT INSIGHTS:
-----------------------------------------------------
${record.investmentInsights.map((ins, i) => `• ${ins}`).join("\n")}

AGENT CONTRIBUTIONS:
-----------------------------------------------------
${record.agentContributions.map((ac) => `${ac.agent} (${ac.confidence}% Confidence): ${ac.role} - "${ac.insight}"`).join("\n\n")}

SUGGESTED ACTIONS:
-----------------------------------------------------
${record.suggestedActions.map((act, i) => `${i + 1}. ${act}`).join("\n")}

=====================================================
Generated by FinOS Financial Operating System
Audit Token: FINOS-AUDIT-${record.id.toUpperCase()}-2026
`;
      setGeneratedReportText(reportContent);
      setReportState("ready");
    }, 1600);
  };

  const handleDownloadReport = () => {
    const element = document.createElement("a");
    const file = new Blob([generatedReportText], { type: "text/plain;charset=utf-8" });
    element.href = URL.createObjectURL(file);
    element.download = `FinOS_Report_${record.id}_${Date.now()}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const getAgentColor = (agentName: string) => {
    const ag = ALL_AGENTS.find(
      (a) => a.name.toLowerCase().includes(agentName.toLowerCase()) || a.slug.toLowerCase() === agentName.toLowerCase()
    );
    return ag?.color.primary || "#10b981";
  };

  return (
    <AppShell
      headerTitle="Analysis Dossier"
      headerSubtitle={`Detailed multi-agent findings for "${record.title}"`}
    >
      <div className="space-y-6 max-w-6xl mx-auto">
        {/* Navigation Breadcrumb */}
        <div className="flex items-center justify-between">
          <Link
            href="/analysis/history"
            className="inline-flex items-center gap-2 text-xs font-bold text-slate-500 hover:text-slate-900 dark:hover:text-white transition"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Back to Analysis History</span>
          </Link>

          <div className="flex items-center gap-2">
            <span className="text-xs text-slate-400 font-mono">
              Audit ID: FINOS-{record.id.toUpperCase()}
            </span>
          </div>
        </div>

        {/* Top Header Banner Card */}
        <div className="p-6 rounded-3xl bg-white dark:bg-[#0c1222] border border-slate-200/90 dark:border-slate-800 shadow-xs space-y-4">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <div className="flex flex-wrap items-center gap-2 mb-2">
                <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800">
                  {record.type}
                </span>
                <span className="inline-flex items-center gap-1.5 text-xs text-slate-500 font-medium">
                  <Calendar className="w-3.5 h-3.5 text-slate-400" />
                  <span>{record.date}</span>
                </span>
                <span className="text-slate-300 dark:text-slate-700">•</span>
                <span className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-600 dark:text-emerald-400">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
                  <span>{record.status}</span>
                </span>
              </div>

              <h1 className="text-2xl sm:text-3xl font-black text-slate-950 dark:text-white tracking-tight">
                {record.title}
              </h1>
            </div>

            {/* Top Action CTAs */}
            <div className="flex flex-wrap items-center gap-2.5 self-start md:self-center">
              <button
                type="button"
                onClick={handleRerun}
                disabled={isRerunning}
                className="px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 hover:bg-slate-100 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 text-xs font-bold transition flex items-center gap-2 disabled:opacity-50 cursor-pointer shadow-2xs"
              >
                {isRerunning ? (
                  <>
                    <Loader2 className="w-3.5 h-3.5 animate-spin" />
                    <span>Analyzing...</span>
                  </>
                ) : (
                  <>
                    <RotateCcw className="w-3.5 h-3.5" />
                    <span>Re-run Analysis</span>
                  </>
                )}
              </button>

              {reportState === "idle" && (
                <button
                  type="button"
                  onClick={handleGenerateReport}
                  className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold transition flex items-center gap-2 shadow-md shadow-emerald-600/20 cursor-pointer"
                >
                  <FileText className="w-3.5 h-3.5" />
                  <span>Generate Report</span>
                </button>
              )}

              {reportState === "generating" && (
                <button
                  disabled
                  className="px-4 py-2 rounded-xl bg-emerald-600/70 text-white text-xs font-bold flex items-center gap-2"
                >
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  <span>Generating Dossier...</span>
                </button>
              )}

              {reportState === "ready" && (
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={handleDownloadReport}
                    className="px-3.5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold flex items-center gap-1.5 shadow-md shadow-emerald-600/20 transition cursor-pointer"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Download Report</span>
                  </button>
                </div>
              )}
            </div>
          </div>

          {/* Original Query Box */}
          <div className="p-3.5 rounded-2xl bg-slate-50 dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 flex items-start gap-3">
            <div className="p-1.5 rounded-lg bg-emerald-50 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 shrink-0 mt-0.5">
              <Bot className="w-4 h-4" />
            </div>
            <div>
              <div className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                Original User Query
              </div>
              <p className="text-xs sm:text-sm font-semibold text-slate-900 dark:text-white mt-0.5">
                &ldquo;{record.query}&rdquo;
              </p>
            </div>
          </div>

          {/* Agents Used Tags */}
          <div className="flex flex-wrap items-center gap-2 pt-1 border-t border-slate-100 dark:border-slate-800 text-xs">
            <span className="font-semibold text-slate-500 dark:text-slate-400">Agents Activated:</span>
            {record.agentsUsed.map((agentName, idx) => (
              <span
                key={idx}
                className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-semibold bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-800 dark:text-slate-200 shadow-2xs"
              >
                <span
                  className="w-2 h-2 rounded-full"
                  style={{ backgroundColor: getAgentColor(agentName) }}
                />
                <span>{agentName}</span>
              </span>
            ))}
          </div>

          {/* Re-run Progress Simulation Banner */}
          {isRerunning && (
            <div className="p-4 rounded-2xl bg-emerald-50/50 dark:bg-emerald-950/30 border border-emerald-500/30 space-y-2 animate-in fade-in">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-emerald-800 dark:text-emerald-300">
                  Executing Autonomous Orchestration...
                </span>
                <Loader2 className="w-4 h-4 text-emerald-600 animate-spin" />
              </div>
              <p className="text-xs font-mono text-emerald-700 dark:text-emerald-400">
                {rerunStage}
              </p>
            </div>
          )}
        </div>

        {/* Executive Summary */}
        <div className="p-6 rounded-3xl bg-[#f0fbf5] dark:bg-[#071912] border border-[#a7f3d0] dark:border-[#065f46]/50 shadow-xs space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
              <h2 className="text-sm font-bold uppercase tracking-wider text-emerald-800 dark:text-emerald-300">
                Executive Consensus Summary
              </h2>
            </div>
            <span className="text-xs font-mono font-bold text-emerald-700 dark:text-emerald-400 bg-white/80 dark:bg-slate-900/80 px-2.5 py-0.5 rounded-full border border-emerald-300/60">
              High Confidence
            </span>
          </div>
          <p className="text-sm text-slate-800 dark:text-slate-200 leading-relaxed font-medium">
            {record.summary}
          </p>
        </div>

        {/* Market Information & Key Stats (if present) */}
        {record.marketInfo && (
          <div className="p-5 rounded-3xl bg-white dark:bg-[#0c1222] border border-slate-200/90 dark:border-slate-800 shadow-xs space-y-3">
            <div className="text-xs font-bold uppercase tracking-wider text-slate-400">
              Live Market Telemetry &amp; Valuation Multiples
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
              {record.marketInfo.symbol && (
                <div className="p-3 rounded-2xl bg-slate-50 dark:bg-slate-900 border border-slate-200/70 dark:border-slate-800">
                  <div className="text-[10px] uppercase font-bold text-slate-400">Symbol</div>
                  <div className="text-sm font-black text-slate-900 dark:text-white mt-0.5">
                    {record.marketInfo.symbol}
                  </div>
                </div>
              )}
              {record.marketInfo.price && (
                <div className="p-3 rounded-2xl bg-slate-50 dark:bg-slate-900 border border-slate-200/70 dark:border-slate-800">
                  <div className="text-[10px] uppercase font-bold text-slate-400">Last Price</div>
                  <div className="text-sm font-black text-slate-900 dark:text-white mt-0.5">
                    {record.marketInfo.price}
                  </div>
                  {record.marketInfo.change && (
                    <div className="text-[10px] text-emerald-600 font-semibold mt-0.5">
                      {record.marketInfo.change}
                    </div>
                  )}
                </div>
              )}
              {record.marketInfo.peRatio && (
                <div className="p-3 rounded-2xl bg-slate-50 dark:bg-slate-900 border border-slate-200/70 dark:border-slate-800">
                  <div className="text-[10px] uppercase font-bold text-slate-400">P/E Multiple</div>
                  <div className="text-sm font-black text-slate-900 dark:text-white mt-0.5">
                    {record.marketInfo.peRatio}
                  </div>
                </div>
              )}
              {record.marketInfo.marketCap && (
                <div className="p-3 rounded-2xl bg-slate-50 dark:bg-slate-900 border border-slate-200/70 dark:border-slate-800">
                  <div className="text-[10px] uppercase font-bold text-slate-400">Market Cap</div>
                  <div className="text-sm font-black text-slate-900 dark:text-white mt-0.5">
                    {record.marketInfo.marketCap}
                  </div>
                </div>
              )}
              {record.marketInfo.volume && (
                <div className="p-3 rounded-2xl bg-slate-50 dark:bg-slate-900 border border-slate-200/70 dark:border-slate-800">
                  <div className="text-[10px] uppercase font-bold text-slate-400">Liquidity Volume</div>
                  <div className="text-sm font-black text-slate-900 dark:text-white mt-0.5">
                    {record.marketInfo.volume}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Dual Grid: Key Findings & Risk Factors */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-stretch">
          {/* Key Findings */}
          <div className="p-6 rounded-3xl bg-white dark:bg-[#0c1222] border border-slate-200/90 dark:border-slate-800 shadow-xs space-y-4 flex flex-col justify-between">
            <div>
              <div className="flex items-center gap-2 mb-3">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 dark:text-white">
                  Key Findings &amp; Core Data Points
                </h3>
              </div>
              <div className="space-y-3">
                {record.keyFindings.map((finding, idx) => (
                  <div key={idx} className="flex items-start gap-2.5 text-xs text-slate-700 dark:text-slate-300">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 shrink-0 mt-1.5" />
                    <span>{finding}</span>
                  </div>
                ))}
              </div>
            </div>

            {record.investmentInsights.length > 0 && (
              <div className="mt-4 pt-4 border-t border-slate-100 dark:border-slate-800">
                <div className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                  Investment Valuation Insights
                </div>
                <div className="space-y-1.5">
                  {record.investmentInsights.map((ins, idx) => (
                    <p key={idx} className="text-xs text-slate-700 dark:text-slate-300">
                      {ins}
                    </p>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Risk Factors */}
          <div className="p-6 rounded-3xl bg-white dark:bg-[#0c1222] border border-slate-200/90 dark:border-slate-800 shadow-xs space-y-4">
            <div className="flex items-center gap-2 mb-1">
              <ShieldAlert className="w-4 h-4 text-rose-600 dark:text-rose-400" />
              <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 dark:text-white">
                Identified Risk Factors
              </h3>
            </div>
            <div className="space-y-3">
              {record.riskFactors.map((risk, idx) => {
                const isHigh = risk.impact === "High";
                const isMed = risk.impact === "Medium";
                return (
                  <div
                    key={idx}
                    className={`p-3.5 rounded-2xl border text-xs ${
                      isHigh
                        ? "bg-rose-50/50 dark:bg-rose-950/20 border-rose-200 dark:border-rose-900/60"
                        : isMed
                        ? "bg-amber-50/50 dark:bg-amber-950/20 border-amber-200 dark:border-amber-900/60"
                        : "bg-slate-50 dark:bg-slate-900 border-slate-200 dark:border-slate-800"
                    }`}
                  >
                    <div className="flex items-center justify-between gap-2 mb-1">
                      <span className="font-bold text-slate-900 dark:text-white">
                        {risk.factor}
                      </span>
                      <span
                        className={`text-[9px] font-bold uppercase px-2 py-0.5 rounded-full ${
                          isHigh
                            ? "bg-rose-100 dark:bg-rose-900/60 text-rose-700 dark:text-rose-300"
                            : isMed
                            ? "bg-amber-100 dark:bg-amber-900/60 text-amber-700 dark:text-amber-300"
                            : "bg-slate-200 dark:bg-slate-800 text-slate-700 dark:text-slate-300"
                        }`}
                      >
                        {risk.impact} Impact
                      </span>
                    </div>
                    <p className="text-slate-600 dark:text-slate-400">
                      {risk.description}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Real-Time News Stream (if available) */}
        {record.news && record.news.length > 0 && (
          <div className="p-6 rounded-3xl bg-white dark:bg-[#0c1222] border border-slate-200/90 dark:border-slate-800 shadow-xs space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 dark:text-white">
                Contextual News &amp; Sentiment Stream
              </h3>
              <span className="text-[11px] text-slate-400 font-mono">NLP Filtered</span>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              {record.news.map((item, idx) => (
                <div
                  key={idx}
                  className="p-3.5 rounded-2xl bg-slate-50 dark:bg-slate-900 border border-slate-200/70 dark:border-slate-800 flex flex-col justify-between text-xs space-y-2"
                >
                  <p className="font-bold text-slate-900 dark:text-white line-clamp-2">
                    {item.headline}
                  </p>
                  <div className="flex items-center justify-between text-[10px] text-slate-400 pt-1 border-t border-slate-200/50 dark:border-slate-800">
                    <span>{item.source} • {item.time}</span>
                    <span
                      className={`font-bold px-1.5 py-0.2 rounded ${
                        item.sentiment === "Positive"
                          ? "bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-400"
                          : item.sentiment === "Negative"
                          ? "bg-rose-50 dark:bg-rose-950/60 text-rose-700 dark:text-rose-400"
                          : "bg-slate-200 dark:bg-slate-800 text-slate-600 dark:text-slate-400"
                      }`}
                    >
                      {item.sentiment}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Agent Contributions Breakdown */}
        <div className="p-6 rounded-3xl bg-white dark:bg-[#0c1222] border border-slate-200/90 dark:border-slate-800 shadow-xs space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 dark:text-white">
                Detailed Agent Contributions
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                Explainable breakdown of individual reasoning and factor weights
              </p>
            </div>
            <span className="text-xs font-mono text-emerald-600 dark:text-emerald-400 font-bold">
              {record.agentContributions.length} Contributors
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-3.5">
            {record.agentContributions.map((contrib, idx) => (
              <div
                key={idx}
                className="p-4 rounded-2xl bg-slate-50/70 dark:bg-slate-900/60 border border-slate-200/80 dark:border-slate-800 space-y-2 flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between gap-2 mb-1.5">
                    <span className="font-bold text-xs text-slate-900 dark:text-white flex items-center gap-1.5">
                      <span
                        className="w-2 h-2 rounded-full"
                        style={{ backgroundColor: getAgentColor(contrib.agent) }}
                      />
                      <span>{contrib.agent}</span>
                    </span>
                    <span className="text-[10px] font-mono font-bold px-1.5 py-0.5 rounded bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300">
                      {contrib.confidence}% Conf.
                    </span>
                  </div>
                  <div className="text-[10px] text-slate-400 uppercase font-semibold mb-2">
                    {contrib.role}
                  </div>
                  <p className="text-xs text-slate-700 dark:text-slate-300 leading-snug">
                    &ldquo;{contrib.insight}&rdquo;
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Suggested Actions Card */}
        <div className="p-6 rounded-3xl bg-slate-900 text-white space-y-4">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5 text-emerald-400" />
            <h3 className="text-sm font-bold uppercase tracking-wider text-emerald-400">
              Recommended Next Actions
            </h3>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            {record.suggestedActions.map((action, idx) => (
              <div
                key={idx}
                className="p-3.5 rounded-2xl bg-slate-800/90 border border-slate-700/80 text-xs text-slate-200 flex items-start gap-2.5"
              >
                <ArrowRight className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                <span>{action}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </AppShell>
  );
}
