import { ReportItem, ReportType } from "@/types/report";
import { MOCK_REPORTS } from "@/lib/mock/reports";
import { AgentId } from "@/types/agent";

export const reportsApi = {
  /**
   * Fetch all generated financial reports.
   */
  async getReports(typeFilter?: ReportType | "All"): Promise<ReportItem[]> {
    return new Promise((resolve) => {
      setTimeout(() => {
        if (!typeFilter || typeFilter === "All") {
          resolve([...MOCK_REPORTS]);
        } else {
          resolve(MOCK_REPORTS.filter((r) => r.type === typeFilter));
        }
      }, 100);
    });
  },

  /**
   * Fetch a single report by ID.
   */
  async getReportById(id: string): Promise<ReportItem | null> {
    const report = MOCK_REPORTS.find((r) => r.id === id);
    return report ? { ...report } : null;
  },

  /**
   * Request generation of a new financial report.
   */
  async generateReport(params: {
    title: string;
    type: ReportType;
    contributingAgents: AgentId[];
  }): Promise<ReportItem> {
    return new Promise((resolve) => {
      setTimeout(() => {
        const newReport: ReportItem = {
          id: `rep-${Date.now().toString().slice(-4)}`,
          title: params.title,
          subtitle: `Generated by ${params.contributingAgents.length} specialized FinOS AI Agents`,
          type: params.type,
          generatedDate: "Just now",
          contributingAgents: params.contributingAgents,
          status: "Ready",
          format: "PDF",
          fileSize: "2.4 MB",
          highlights: [
            "Executive summary compiled from live agent telemetry.",
            "All risk guardrails and factor loadings validated.",
            "Export ready for institutional investment committee.",
          ],
        };
        MOCK_REPORTS.unshift(newReport);
        resolve(newReport);
      }, 900);
    });
  },
};
